# Knowledge Hub Auto-Update Script (PowerShell Edition)
$ErrorActionPreference = "Stop"

# Helper to decode UTF-8 strings from Base64 to prevent encoding corruption in PowerShell
function Get-Utf8String($base64) {
    $bytes = [System.Convert]::FromBase64String($base64)
    return [System.Text.Encoding]::UTF8.GetString($bytes)
}

# Base64 values for Chinese strings
$dirName = Get-Utf8String "55+l6K2Y5YiG5Lqr5Y2A" # "知識分享區"
$noDescText = Get-Utf8String "54Sh5o+Q5L6b57Ch5LuL" # "無提供簡介"

$KnowledgeDir = Join-Path $PSScriptRoot $dirName
$OutputFile = Join-Path $KnowledgeDir "knowledge-data.js"

Write-Host "Scanning directory: $dirName ..." -ForegroundColor Green

if (-not (Test-Path $KnowledgeDir)) {
    Write-Error "Directory not found: $KnowledgeDir"
    exit 1
}

$htmlFiles = Get-ChildItem -Path $KnowledgeDir -Filter "*.html" | Where-Object { $_.Name -ne "index.html" }
Write-Host "Found $($htmlFiles.Count) HTML file(s)" -ForegroundColor Green

$dataList = [System.Collections.Generic.List[PSCustomObject]]::new()

foreach ($file in $htmlFiles) {
    try {
        $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
        
        # 1. Get Title
        $title = ""
        if ($content -match '<title>([\s\S]*?)<\/title>') {
            $title = $Matches[1].Trim() -replace '\s+', ' '
        } else {
            $title = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
        }

        # 2. Get Summary / Description
        $summary = ""
        
        # A. Try meta description
        if ($content -match '<meta\s+name=["'']description["'']\s+content=["'']([\s\S]*?)["'']' -or $content -match '<meta\s+content=["'']([\s\S]*?)["'']\s+name=["'']description["'']') {
            $summary = $Matches[1].Trim()
        }
        # B. Try HTML comment <!-- summary: ... -->
        elseif ($content -match '<!--\s*summary:\s*([\s\S]*?)\s*-->') {
            $summary = $Matches[1].Trim()
        }
        # C. Try element with class="subtitle"
        elseif ($content -match 'class=["'']subtitle["''][^>]*>([\s\S]*?)<\/(?:p|div|span)>') {
            $summary = $Matches[1].Trim() -replace '<[^>]+>', ''
        }
        # D. Fallback: Grab first 60 chars from body
        else {
            if ($content -match '<body[\s\S]*?>([\s\S]*?)<\/body>') {
                $bodyText = $Matches[1] -replace '<script[\s\S]*?<\/script>', '' -replace '<style[\s\S]*?<\/style>', '' -replace '<[^>]+>', '' -replace '\s+', ' '
                $bodyText = $bodyText.Trim()
                if ($bodyText.Length -gt 60) {
                    $summary = $bodyText.Substring(0, 60) + "..."
                } else {
                    $summary = $bodyText
                }
            } else {
                $summary = $noDescText
            }
        }

        if (-not $summary) {
            $summary = $noDescText
        } else {
            $summary = $summary -replace '\s+', ' '
        }

        # 3. Get Date
        $dateStr = ""
        if ($content -match '<!--\s*date:\s*(\d{4}-\d{2}-\d{2})\s*-->') {
            $dateStr = $Matches[1].Trim()
        } else {
            $dateStr = $file.LastWriteTime.ToString("yyyy-MM-dd")
        }

        $dataList.Add([PSCustomObject]@{
            filename = $file.Name
            title    = $title
            summary  = $summary
            date     = $dateStr
            path     = "$dirName/$($file.Name)"
        })
        
        Write-Host "- Parsed [$title]" -ForegroundColor Cyan
    }
    catch {
        Write-Warning "Failed to parse file: $($file.Name). Error: $_"
    }
}

# Sort by date descending
$sortedList = $dataList | Sort-Object -Property date -Descending

# Convert to JSON
$jsonPretty = ConvertTo-Json @($sortedList) -Depth 3

# Write JS file
$outputContent = @"
// This file is auto-generated by update_knowledge.ps1. Do not edit manually.
// Generated on $((Get-Date).ToString("yyyy-MM-dd"))
const KNOWLEDGE_DATA = $jsonPretty;
"@

[System.IO.File]::WriteAllText($OutputFile, $outputContent, [System.Text.Encoding]::UTF8)

Write-Host "Success! Created: $OutputFile" -ForegroundColor Green
