// This file is auto-generated by update_knowledge.ps1. Do not edit manually.
// Generated on 2026-07-05
const KNOWLEDGE_DATA = [
    {
        "filename":  "台灣綠電市場.html",
        "title":  "台灣綠電市場洞察簡報｜國富浩華 Crowe (TW)",
        "summary":  "解讀資策會《台灣綠電市場手冊》，聚焦企業綠電採購的核心洞見、關鍵數據與可執行的行動建議。",
        "date":  "2026-07-04",
        "path":  "知識分享區/台灣綠電市場.html"
    }
];